services:
  app-backend:
    ports:
      - "8000:8000"
    image: "alejovicu/app-backend:1.0.3"
  app-frontend:
    ports:
      - "80:5173"
    environment:
      - VITE_BACKEND_URL=http://localhost:8000
    image: "alejovicu/app-frontend:1.0.3"
  jenkins:
    ports:
      - "8080:8080"
    # CHANGED THIS LINE:
    image: "jenkins/jenkins:lts-jdk17"
    # OR use platform flag to force AMD64 emulation:
    # platform: linux/amd64
    volumes:
      - jenkins_home:/var/jenkins_home
  mailhog:
    container_name: mailhog
    image: mailhog/mailhog
    ports:
      - "8025:8025"
      - "1025:1025"

volumes:
  jenkins_home: